### ISSUE TITLE
No tab

### ISSUE THREAD

**Issue by M4nimal** [kmgalanakis/Inceptive-Multiple-Categories-for-K2#3]
Hello

Joomla! 3.6.5
K2 v2.7.1

After installing the plugin, I dont see the tab "Inceptive Multiple Categories for K2" while editing an Item. Please assist?

**Comment by kmgalanakis** [comment]
This is strange.

I've tested once again on a vanilla Joomla v3.6.5 installation, K2 v2.7.1 and Inceptive Multiple Categories for K2 v1.3 and the tab appears fine.

Do you get any jQuery errors in your Developer Tools console?

**Comment by kmgalanakis** [comment]
It seems we can consider this solved.
