### ISSUE TITLE
Display categories on the frontend

### ISSUE THREAD

**Issue by JeroenMoolenschot** [kmgalanakis/Inceptive-Multiple-Categories-for-K2#5]
Hi,

Thanks for this great plugin!
Can you tell me what's the best way to do this?

My client shows the category of the article on his website like
![afbeelding](https://user-images.githubusercontent.com/1471185/27645297-06ecab50-5c26-11e7-901d-8ecf82d98300.png)

Is it possible to add the multiple categories from your plugin (comma seperated) to the main-category?

**Comment by kmgalanakis** [comment]
Hello. If I understand correctly what you are trying to do, I would say that you cannot do it out of the box. You need to add custom code. But before helping you with that, how about you further explain your setup in order to reproduce it locally and try to write the code locally as well?
