### ISSUE TITLE
Cant Manually Sort K2 items

### ISSUE THREAD

**Issue by PixelPerfectCreative** [kmgalanakis/Inceptive-Multiple-Categories-for-K2#9]
Hi there, I can no longer do a manual sort of my K2 items. When I click on the arrows to be able to sort them I get an error. You can see in the image below what is happening. If I turn on Inceptive Multiple Categories, I can then sort normally, with no error.  I brought this up on the K2 forum and they suggested I contact you first... https://www.joomlaworks.net/forum/k2-en/48473-user-ordering#165312

I am using this for my largest client and they need to be able to sort the items, AND have multiple categories. They have over a thousand items, so switching so another plugin, or hacking the code to achieve this would be a huge ordeal. 

Any help would be greatly appreciated. 

Thanks!

![3zhwe0ug](https://user-images.githubusercontent.com/22380217/32860222-985b450c-ca16-11e7-8965-e45718fb3c2e.jpg)

**Comment by PixelPerfectCreative** [comment]
Any chance of getting help here? Thanks in advance for any update.

**Comment by bositman** [comment]
In incptvk2multiplecategories.php , on line 82 try replacing
$query = str_replace("ORDER BY i.catid","ORDER BY mc.catid",$query);
with
$query = str_replace("ORDER BY i.catid","ORDER BY mc.catID",$query);

**Comment by kmgalanakis** [comment]
@PixelPerfectCreative, @bositman suggestion seems to be correct, have you tried it yet? Did it solve your issue?

**Comment by franco2mada** [comment]
has the same problem;
the solution from @bositman  works

> In incptvk2multiplecategories.php , on line 82 try replacing
$query = str_replace("ORDER BY i.catid","ORDER BY mc.catid",$query);
with
$query = str_replace("ORDER BY i.catid","ORDER BY mc.catID",$query);

**Comment by kmgalanakis** [comment]
This is fixed by https://github.com/kmgalanakis/Inceptive-Multiple-Categories-for-K2/commit/0e890d0578cff3d0746430fa63327c164df7e0dd.

I'm closing this.
